create table if not exists public.song_keys (
  id bigint generated by default as identity primary key,
  spotify_id text unique,
  musicbrainz_id text unique,
  isrc text,
  title text not null,
  artist text not null,
  album text,
  key_root smallint not null check (key_root between 0 and 11),
  mode text not null check (mode in ('major','minor')),
  progression text,
  confidence smallint not null default 70 check (confidence between 0 and 100),
  source text not null default 'community',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists song_keys_isrc_idx on public.song_keys(isrc);
create index if not exists song_keys_title_artist_idx on public.song_keys(lower(title),lower(artist));

create table if not exists public.saved_songs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  song_key_id bigint references public.song_keys(id) on delete set null,
  title text not null,
  artist text not null,
  progression text not null,
  source_key smallint not null check (source_key between 0 and 11),
  mode text not null check (mode in ('major','minor')),
  target_key smallint not null check (target_key between 0 and 11),
  capo smallint not null default 0 check (capo between 0 and 11),
  created_at timestamptz not null default now()
);

create index if not exists saved_songs_user_idx on public.saved_songs(user_id,created_at desc);
alter table public.song_keys enable row level security;
alter table public.saved_songs enable row level security;

create policy "Anyone can read song keys" on public.song_keys for select using (true);
create policy "Signed in users can add song keys" on public.song_keys for insert to authenticated with check (auth.uid()=created_by);
create policy "Users read their saved songs" on public.saved_songs for select to authenticated using (auth.uid()=user_id);
create policy "Users save their own songs" on public.saved_songs for insert to authenticated with check (auth.uid()=user_id);
create policy "Users delete their own songs" on public.saved_songs for delete to authenticated using (auth.uid()=user_id);
